### ISSUE TITLE
Open redirect vulnerability

### ISSUE THREAD

**Issue by Guezone** [flask-extensions/flask_simplelogin#21]
First of all, thank you for the work! For the detail, there is an Open Redirect vulnerability in flask_simplelogin when authenticating after trying to access a page where the @login_required directive is set. An attacker can then send a link to : https://goodsite.com/login/?next=https://badsite.com/login -> The user authenticates and is then redirected to the wrong site with the same appearance (potentially) indicating for example "login failed", he then retypes his credentials and that's it for the attacker... 

I think it would be interesting to allow redirection only if the "next url" is "routable".

**Comment by cuducos** [comment]
That's great. Just think out loud, a way to verify that in `SimpleLogin.login` method:

```python
        safe = False
        for rule in self.app.url_map.iter_rules():
            if rule.match(destiny):
                safe = True
                break

        if not safe:
            # TODO raise 404, specific error, or redirect do home?
```

**Comment by Guezone** [comment]
Thank you very much !
