### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by anapaulagomes** [flask-extensions/flask_simplelogin#22]
Thanks for creating such nice extension! 🏆  I'd like to list here what I think would be nice to have in a documentation page.

* Introduction: What this extension is about and which problem it solves
* How to install the extension
* Examples
* Troubleshooting

The README already have most of it covered but it's handy to have a documentation where we can search for terms, see the pages available and go directly for what we're looking for.
Here a nice example of documentation: https://dramatiq.io/ (IMHO) They use Sphinx to generate it.

**Comment by cuducos** [comment]
Closed by #23
